---

- name: Configuring module
  template:
    src: "etc/php/7.0/mods-available/newrelic.ini.j2"
    dest: "{{ php7_newrelic_config_dest }}/newrelic.ini"
    owner: "root"
    group: "root"
    mode: "0644"
  when: "not php7_newrelic_php_daemon_notify|bool"

- name: Configuring module
  template:
    src: "etc/php/7.0/mods-available/newrelic.ini.j2"
    dest: "{{ php7_newrelic_config_dest }}/newrelic.ini"
    owner: "root"
    group: "root"
    mode: "0644"
  when: "php7_newrelic_php_daemon_notify|bool"
  notify: "{{ php7_newrelic_php_daemon_notify_handler }}"
